# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KzQhm1PXIEmI4PbaC-OWRvG5JiJPkyNn
"""

import matplotlib.pyplot as plt
grades = [2, 3, 3, 2, 5, 5, 3, 4, 5, 4]
plt.hist(grades, bins=[2, 3, 4, 5, 6], edgecolor='black')
plt.xlabel('Оценки')
plt.ylabel('Количество учеников')
plt.titile('Распределение оценок по матиматике в классе')
plt.show()

import numpy as np
random_array = np.random.randint(1, 11, size=(4, 4))
print(random_array)

import matplotlib.pvplot as plt
total_students = 32
boys = 15
girls = 17
labels = ['Мальчики', 'Девочки']
sizes = [boys, girls]
colors = ['blue', 'pink']
plt.p1e(sizes, labels=labels, colors=colors, autopct='%1.1%%', startangle=90)
plt.axis('equal') # Равные оси, чтобы круг был кругом
plt.title('Соотношение мальчиков и девочек в классе')
plt.show()